name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 21.x, 22.x]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.0
      -
        name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Install Dependencies
        run: npm install
      -
        name: Run Build
        run: npm run build
      -
        name: Unit Tests with Coverage
        run: npm run test:cov
